config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :partners
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   #root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :partner_customers
    has_many :partners, through: :partner_customers
end

app/models/partner.rb
class Partner < ApplicationRecord
    has_many :partner_customers
    has_many :customers, through: :partner_customers
    belongs_to :user

   
end

app/models/partner_customer.rb
class PartnerCustomer < ApplicationRecord
  belongs_to :partner
  belongs_to :customer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :partners

  private
  
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
    
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /partners or /partners.json
  def index
    @partners = Partner.all
  end

  # GET /partners/1 or /partners/1.json
  def show
    render(partial: 'show') if request.xhr?
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners or /partners.json
  def create
    @partner = Partner.new(partner_params)
    

    respond_to do |format|
      if @partner.save
        format.html { redirect_to partner_url(@partner), notice: "Partner was successfully created." }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1 or /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to partner_url(@partner), notice: "Partner was successfully updated." }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1 or /partners/1.json
  def destroy
    @partner.destroy

    respond_to do |format|
      format.html { redirect_to partners_url, notice: "Partner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def partner_params
      params.require(:partner).permit(:name, :address, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= customer.name %>
  </p>
  

  <% if action_name != "show" %>
    <%= link_to "Show this customer", customer, remote: true %>
    <%= link_to 'Edit this customer', edit_customer_path(customer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer, class: "contents") do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing customer</h1>

  <%= render "form", customer: @customer %>

  <%= link_to "Show this customer", @customer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to customers", customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/customers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Customers</h1>
    <%= link_to 'New customer', new_customer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="customers" class="min-w-full">
    <%= render @customers %>
  </div>
</div>

app/views/customers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New customer</h1>

  <%= render "form", customer: @customer %>

  <%= link_to 'Back to customers', customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/customers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @customer %>
    <p>
      <h2>Especialidad</h2>
      <ul>
        <% @customer.partners.each do |partner| %>
          <li><%= partner.name %></li>
        <% end %>
      </ul>
  </p>

    <%= link_to 'Edit this customer', edit_customer_path(@customer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this customer', customer_path(@customer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to customers', customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %><p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'shared/nabvar'%>
      <%= render 'layouts/alerts'%>
      </header>

    
    <main class="container mx-auto mt-5 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class=container>

<% if current_user %>
    <p>Hello <%= current_user.email %>!</p>
    <p>You are a [<%= current_user.role %>]
    <% if current_user.admin? %>
    <br/>
        There are <%= User.count %> users in the system.
    <% end %>

    <p> 
      You have successfully.
      You are now ready
    </p>
    <%= link_to "Sign out", destroy_user_session_path, 'data-turbo-method': :delete %>
    <%= link_to "Edit Account", edit_user_registration_path %>
<% else %>

    <p>You are not signed in.</p>
    <%= link_to "Sign Up!", new_user_registration_path %>
    <br />
    <%= link_to "Login", new_user_session_path %>


<% end %>

</div>

app/views/partners/_form.html.erb
<%= form_with(model: partner, class: "contents") do |form| %>
  <% if partner.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
        <% partner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/partners/_partner.html.erb
<div id="<%= dom_id partner %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <h2><%= partner.name %></h2>
    <h4> posted by <%= partner.user%></h4>
    
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= partner.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= partner.city %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this partner", partner, remote: true, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this partner', edit_partner_path(partner), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/partners/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing partner</h1>

  <%= render "form", partner: @partner %>

  <%= link_to "Show this partner", @partner, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to partners", partners_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/partners/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Partners</h1>
    <%= link_to 'New partner', new_partner_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="partners" class="min-w-full">
    <%= render @partners %>
  </div>
</div>

app/views/partners/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New partner</h1>

  <%= render "form", partner: @partner %>

  <%= link_to 'Back to partners', partners_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/partners/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @partner %>

    <%= link_to 'Edit this partner', edit_partner_path(@partner), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this partner', partner_path(@partner), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to partners', partners_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shared/_nabvar.html.erb
<nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    
    <span class="font-semibold text-xl tracking-tight"></span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">

     <%= link_to "Home", root_path, class:"block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
     
      <%= link_to "Clientes", customers_path, class:"block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"%>
        
      </a>
      <%= link_to "Partners", partners_path, class:"block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4" %>
        
      </a>

      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
        SignUp
      </a>
    </div>
    <div>
      <ul class="navbar-nav">
        <%= render 'user/session_manager'%>
        
      </ul>
    </div>
      

       
  </div>
</nav>

    

app/views/user/_session_manager.html.erb
<% if current_user %>
<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User funtionality
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelldby="navbarDropdown">
            <li><%= link_to "New partner", new_partner_path, class: "dropdown-item" %>
                <li><%= link_to "New customer", new_customer_path, class: "dropdown-ite" %></li>
                <li><%= link_to "Edit Account", edit_user_registration_path,class: "dropdown-ite" %></li>
                <li><a class="dropdown-item" href="#">Another action</a><li>
                <li><hr class="dropdown-divider"></li>
                
                <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %><li>
            </ul>
          </li>
<% else %>
    <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
    </li>

<% end %>